/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:PolyCalc:351788:
  appc.background(128);
} //_CODE_:PolyCalc:351788:

public void inputPoly1(GTextField source, GEvent event) { //_CODE_:polyText1:479189:
  s1 = polyText1.getText();
  a = new Polynomial(s1);
  a.printPoly();
} //_CODE_:polyText1:479189:

public void dropBox1(GDropList source, GEvent event) { //_CODE_:dropbox:816754:
  //println(dropbox.getSelectedIndex());
  if(dropbox.getSelectedIndex() == 1){ //add
    aAndB = a.add(b);
    aAndB.printPoly();
  }else if(dropbox.getSelectedIndex() == 2){ //subtract
    aAndB = a.sub(b);
    aAndB.printPoly();
  }else if(dropbox.getSelectedIndex() == 3){ //multiply
    aAndB = a.mult(b);
    aAndB.printPoly();
  }
  
} //_CODE_:dropbox:816754:

public void inputPoly2(GTextField source, GEvent event) { //_CODE_:polyText2:232081:
  s2 = polyText2.getText();
  b = new Polynomial(s2);
  b.printPoly();
} //_CODE_:polyText2:232081:

public void poly1info_change1(GTextArea source, GEvent event) { //_CODE_:Poly1Info:245290:
  println("Poly1Info:");
  a.roots();
  aDerive = a.derive();
  aDerive.printPoly();
  Poly1Info.setText(roots + "\nDerivative: " + polyPrint);
  
  //print roots, max/min
} //_CODE_:Poly1Info:245290:

public void poly2info_change1(GTextArea source, GEvent event) { //_CODE_:Poly2Info:543126:
  println("Poly2Info:");
  b.roots();
  bDerive = b.derive();
  bDerive.printPoly();
  Poly2Info.setText(roots + "\nDerivative: " + polyPrint);
  //print roots, max/min;
} //_CODE_:Poly2Info:543126:

public void answer_output(GTextField source, GEvent event) { //_CODE_:answerText:599394:
  answerText.setText(polyPrint);
} //_CODE_:answerText:599394:

public void poly3info_change1(GTextArea source, GEvent event) { //_CODE_:Poly3Info:534073:
  println("Poly3Info:");
  aAndB.roots();
  Poly3Info.setText(roots);
} //_CODE_:Poly3Info:534073:

public void min1_change1(GTextField source, GEvent event) { //_CODE_:min1:762714:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:min1:762714:

public void max1_change1(GTextField source, GEvent event) { //_CODE_:max1:528066:
  println("max1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:max1:528066:

public void min2_change1(GTextField source, GEvent event) { //_CODE_:min2:804767:
  println("min2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:min2:804767:

public void max2_change1(GTextField source, GEvent event) { //_CODE_:max2:669949:
  println("max2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:max2:669949:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  PolyCalc = GWindow.getWindow(this, "PolyCalc2", 0, 0, 550, 500, JAVA2D);
  PolyCalc.noLoop();
  PolyCalc.setActionOnClose(G4P.KEEP_OPEN);
  PolyCalc.addDrawHandler(this, "win_draw1");
  title = new GLabel(PolyCalc, 208, 22, 108, 28);
  title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  title.setText("PolyCalc 2.0");
  title.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  title.setOpaque(true);
  polyText1 = new GTextField(PolyCalc, 23, 93, 183, 30, G4P.SCROLLBARS_NONE);
  polyText1.setLocalColorScheme(GCScheme.RED_SCHEME);
  polyText1.setOpaque(true);
  polyText1.addEventHandler(this, "inputPoly1");
  polytext1 = new GLabel(PolyCalc, 23, 64, 164, 20);
  polytext1.setText("Enter Your 1st Polynomial");
  polytext1.setLocalColorScheme(GCScheme.RED_SCHEME);
  polytext1.setOpaque(true);
  dropbox = new GDropList(PolyCalc, 220, 95, 91, 161, 6, 10);
  dropbox.setItems(loadStrings("list_816754"), 0);
  dropbox.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  dropbox.addEventHandler(this, "dropBox1");
  label1 = new GLabel(PolyCalc, 325, 64, 154, 20);
  label1.setText("Enter Your 2nd Polynomial");
  label1.setLocalColorScheme(GCScheme.RED_SCHEME);
  label1.setOpaque(true);
  polyText2 = new GTextField(PolyCalc, 324, 93, 183, 31, G4P.SCROLLBARS_NONE);
  polyText2.setLocalColorScheme(GCScheme.RED_SCHEME);
  polyText2.setOpaque(false);
  polyText2.addEventHandler(this, "inputPoly2");
  Poly1Info = new GTextArea(PolyCalc, 23, 166, 100, 86, G4P.SCROLLBARS_NONE);
  Poly1Info.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Poly1Info.setOpaque(true);
  Poly1Info.addEventHandler(this, "poly1info_change1");
  Poly2Info = new GTextArea(PolyCalc, 324, 167, 103, 82, G4P.SCROLLBARS_NONE);
  Poly2Info.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Poly2Info.setOpaque(true);
  Poly2Info.addEventHandler(this, "poly2info_change1");
  label2 = new GLabel(PolyCalc, 24, 135, 98, 19);
  label2.setText("Polynomial Info:");
  label2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label2.setOpaque(true);
  label3 = new GLabel(PolyCalc, 325, 134, 101, 20);
  label3.setText("Polynomial Info:");
  label3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label3.setOpaque(true);
  label4 = new GLabel(PolyCalc, 35, 271, 456, 19);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("__________________________________________________________________");
  label4.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label4.setOpaque(true);
  label5 = new GLabel(PolyCalc, 44, 309, 80, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Answer:");
  label5.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label5.setOpaque(true);
  answerText = new GTextField(PolyCalc, 142, 303, 322, 35, G4P.SCROLLBARS_NONE);
  answerText.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  answerText.setOpaque(true);
  answerText.addEventHandler(this, "answer_output");
  label6 = new GLabel(PolyCalc, 141, 349, 109, 21);
  label6.setText("Polynomial Info:");
  label6.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label6.setOpaque(true);
  Poly3Info = new GTextArea(PolyCalc, 141, 379, 208, 84, G4P.SCROLLBARS_NONE);
  Poly3Info.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Poly3Info.setOpaque(true);
  Poly3Info.addEventHandler(this, "poly3info_change1");
  min1 = new GTextField(PolyCalc, 139, 161, 69, 26, G4P.SCROLLBARS_NONE);
  min1.setOpaque(true);
  min1.addEventHandler(this, "min1_change1");
  poly1min = new GLabel(PolyCalc, 138, 133, 68, 22);
  poly1min.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  poly1min.setText("Min");
  poly1min.setOpaque(false);
  poly1max = new GLabel(PolyCalc, 139, 195, 68, 21);
  poly1max.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  poly1max.setText("Max");
  poly1max.setOpaque(false);
  max1 = new GTextField(PolyCalc, 139, 223, 68, 27, G4P.SCROLLBARS_NONE);
  max1.setOpaque(true);
  max1.addEventHandler(this, "max1_change1");
  poly2min = new GLabel(PolyCalc, 441, 134, 64, 20);
  poly2min.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  poly2min.setText("Min");
  poly2min.setOpaque(false);
  min2 = new GTextField(PolyCalc, 441, 163, 65, 24, G4P.SCROLLBARS_NONE);
  min2.setOpaque(true);
  min2.addEventHandler(this, "min2_change1");
  poly2max = new GLabel(PolyCalc, 441, 195, 65, 20);
  poly2max.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  poly2max.setText("Max");
  poly2max.setOpaque(false);
  max2 = new GTextField(PolyCalc, 441, 223, 67, 24, G4P.SCROLLBARS_NONE);
  max2.setOpaque(true);
  max2.addEventHandler(this, "max2_change1");
  PolyCalc.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow PolyCalc;
GLabel title; 
GTextField polyText1; 
GLabel polytext1; 
GDropList dropbox; 
GLabel label1; 
GTextField polyText2; 
GTextArea Poly1Info; 
GTextArea Poly2Info; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GTextField answerText; 
GLabel label6; 
GTextArea Poly3Info; 
GTextField min1; 
GLabel poly1min; 
GLabel poly1max; 
GTextField max1; 
GLabel poly2min; 
GTextField min2; 
GLabel poly2max; 
GTextField max2; 
